#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gmqtt
Version  : 0.4.3
Release  : 27
URL      : https://files.pythonhosted.org/packages/9e/4c/5b7945dd94848099c7b33c5b6d6c688420ce5d7069a0ddc27c9a90c6a14f/gmqtt-0.4.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/9e/4c/5b7945dd94848099c7b33c5b6d6c688420ce5d7069a0ddc27c9a90c6a14f/gmqtt-0.4.3.tar.gz
Summary  : Client for MQTT protocol
Group    : Development/Tools
License  : MIT
Requires: gmqtt-license = %{version}-%{release}
Requires: gmqtt-python = %{version}-%{release}
Requires: gmqtt-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
[![Build Status](https://travis-ci.com/wialon/gmqtt.svg?branch=master)](https://travis-ci.com/wialon/gmqtt) [![codecov](https://codecov.io/gh/wialon/gmqtt/branch/master/graph/badge.svg)](https://codecov.io/gh/wialon/gmqtt)

%package license
Summary: license components for the gmqtt package.
Group: Default

%description license
license components for the gmqtt package.


%package python
Summary: python components for the gmqtt package.
Group: Default
Requires: gmqtt-python3 = %{version}-%{release}

%description python
python components for the gmqtt package.


%package python3
Summary: python3 components for the gmqtt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the gmqtt package.


%prep
%setup -q -n gmqtt-0.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570020534
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gmqtt
cp LICENSE %{buildroot}/usr/share/package-licenses/gmqtt/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}/usr/lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.pyc
rm -f %{buildroot}/usr/lib/python3.7/site-packages/tests/__init__.py
rm -f %{buildroot}/usr/lib/python3.7/site-packages/tests/utils.py
rm -f %{buildroot}/usr/lib/python3.7/site-packages/tests/__pycache__/utils.cpython-37.pyc

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gmqtt/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
